import type { Metadata } from "next";
import { Header } from "../components/Header";
import { Footer } from "../components/Footer";
import { SEASONS, seasonSlugs, indexedSeasonalBirds } from "../../lib/seasonal-repository";
import { US_STATES_DATA } from "../../data/us-states-data";

export const metadata:Metadata={title:"Seasonal Birds: Spring, Summer, Fall & Winter Guides",description:"Explore seasonal bird migration, nesting, feeding, and backyard activity guides by season, state, and species.",alternates:{canonical:"/seasonal-birds"}};

export default function SeasonalBirdsHub(){return <div><Header/><main className="content-main"><div className="breadcrumb"><a href="/">Home</a> / Seasonal Birds</div><section className="content-hero"><div><p className="eyebrow"><span/> Seasonal bird guides</p><h1>Birding changes<br/><em>with the season.</em></h1><p className="lede">Explore practical, source-aware guides for migration, nesting, feeding, and backyard bird activity. Start with a season, then narrow by state or a reviewed species.</p></div><aside className="fact-panel"><div><small>Season guides</small><strong>4</strong></div><div><small>State combinations</small><strong>{US_STATES_DATA.length*4}</strong></div><div><small>Reviewed species combinations</small><strong>{indexedSeasonalBirds.length*4}</strong></div></aside></section><div className="content-grid">{seasonSlugs.map(slug=>{const season=SEASONS[slug];return <a className="info-block" href={`/seasonal-birds/${slug}`} key={slug}><p className="eyebrow"><span/> {season.months}</p><h2>{season.name} birds</h2><p>{season.activity}. Support birds with {season.focus}.</p><strong>Explore {season.name.toLowerCase()} →</strong></a>})}<section className="info-block wide"><h2>How these guides are published</h2><p>Season and reviewed species pages are indexable. State combinations remain available for planning but are kept out of search results until licensed, location-specific monthly occurrence data passes the quality gate.</p></section></div></main><Footer/></div>}
