import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { Header } from "../../components/Header";
import { Footer } from "../../components/Footer";
import { EditorialPage, editorialMetadata } from "../../components/Editorial";
import { SeasonTopBirds } from "../../components/SeasonData";
import { seasonalEditorial } from "../../../data/editorial/seasonal";
import { SEASONS, indexedSeasonalBirds, isSeason, seasonSlugs } from "../../../lib/seasonal-repository";
import { US_STATES_DATA } from "../../../data/us-states-data";

export function generateStaticParams(){return seasonSlugs.map(season=>({season}))}
export async function generateMetadata({params}:{params:Promise<{season:string}>}):Promise<Metadata>{const {season}=await params;if(!isSeason(season))return{};const ed=seasonalEditorial[`/seasonal-birds/${season}`];if(ed)return editorialMetadata(ed);const item=SEASONS[season];return{title:`${item.name} Birds: Migration, Feeding & Backyard Guide`,description:`Discover ${item.name.toLowerCase()} birds, migration and nesting activity, feeding priorities, observation tips, and guides by state and species.`,alternates:{canonical:`/seasonal-birds/${season}`}}}

export default async function SeasonPage({params}:{params:Promise<{season:string}>}){const {season}=await params;if(!isSeason(season))notFound();const item=SEASONS[season];const ed=seasonalEditorial[`/seasonal-birds/${season}`];if(ed)return <EditorialPage content={ed} eyebrow={`${item.name} · ${item.months}`} breadcrumbs={[{name:"Seasonal birds",path:"/seasonal-birds"},{name:`${item.name} birds`,path:ed.path}]}><SeasonTopBirds season={season}/><section className="loc-section"><div className="loc-section-header"><h2>{item.name} guides by species</h2></div><div className="chip-list">{indexedSeasonalBirds.map(bird=><a href={`/seasonal-birds/${season}/${bird.slug}`} key={bird.slug}>{bird.commonName} in {item.name.toLowerCase()} →</a>)}{seasonSlugs.filter(x=>x!==season).map(x=><a href={`/seasonal-birds/${x}`} key={x}>{SEASONS[x].name} birds →</a>)}</div></section></EditorialPage>;return <div><Header/><main className="content-main"><div className="breadcrumb"><a href="/">Home</a> / <a href="/seasonal-birds">Seasonal Birds</a> / {item.name}</div><section className="content-hero"><div><p className="eyebrow"><span/> {item.months}</p><h1>{item.name} birds</h1><p className="lede">{item.name} emphasizes {item.activity}. Build your birding and backyard plan around {item.focus}.</p></div><aside className="fact-panel"><div><small>Main activity</small><strong>{item.activity}</strong></div><div><small>Habitat focus</small><strong>{item.focus}</strong></div></aside></section><div className="content-grid"><section className="info-block wide"><h2>Reviewed species guides</h2><div className="index-grid">{indexedSeasonalBirds.map(bird=><a className="index-card" href={`/seasonal-birds/${season}/${bird.slug}`} key={bird.slug}><small>{bird.scientificName}</small><h2>{bird.commonName}</h2><p>{bird.residentStatus}</p><span>{item.name} guide →</span></a>)}</div></section><section className="info-block wide"><h2>{item.name} birds by state</h2><p>State pages are planning previews and remain noindex until location-specific monthly occurrence data is verified.</p><div className="state-directory">{US_STATES_DATA.map(state=><a className="state-card" href={`/seasonal-birds/${season}/${state.slug}`} key={state.slug}><span className="state-card-abbr">{state.abbr}</span><span className="state-card-name">{state.name}</span><span className="state-card-count">{state.flyway} Flyway</span></a>)}</div></section></div></main><Footer/></div>}
