import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Header } from "../../components/Header";
import { Footer } from "../../components/Footer";
import { getBirdBySlug, getBirdStaticParams } from "../../../lib/bird-repository";

export function generateStaticParams(){return getBirdStaticParams()}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const bird=await getBirdBySlug((await params).slug);return bird?{title:`${bird.commonName}: Diet & How to Attract`,description:`Learn where ${bird.commonName}s live, what they eat, and which plants and feeders can help attract them.`}:{}}

export default async function BirdPage({params}:{params:Promise<{slug:string}>}){
  const bird=await getBirdBySlug((await params).slug);if(!bird)notFound();
  return <div><Header/><main className="content-main"><div className="breadcrumb"><Link href="/">Home</Link> / <Link href="/birds">Birds</Link> / {bird.commonName}</div>
    <section className="content-hero"><div><p className="eyebrow"><span/> Reviewed bird profile</p><h1>{bird.commonName}</h1><p className="scientific">{bird.scientificName}</p><p className="lede">{bird.summary}</p></div>{bird.imageUrl?<figure className="bird-profile-image"><img src={bird.imageUrl} alt={bird.imageAlt??bird.commonName}/><figcaption>{bird.imageSourceUrl?<a href={bird.imageSourceUrl} target="_blank" rel="noreferrer">{bird.imageAttribution}</a>:bird.imageAttribution}{bird.imageLicenseUrl&&<> · <a href={bird.imageLicenseUrl} target="_blank" rel="noreferrer">License</a></>}</figcaption></figure>:<aside className="fact-panel"><div><small>Size</small><strong>{bird.size}</strong></div><div><small>Colors</small><strong>{bird.colors}</strong></div><div><small>Useful feeder foods</small><strong>{bird.diet}</strong></div><div><small>Habitat</small><strong>{bird.habitat}</strong></div></aside>}</section>
    {bird.imageUrl&&<aside className="fact-strip"><div><small>Size</small><strong>{bird.size}</strong></div><div><small>Colors</small><strong>{bird.colors}</strong></div><div><small>Useful feeder foods</small><strong>{bird.diet}</strong></div><div><small>Habitat</small><strong>{bird.habitat}</strong></div></aside>}
    <div className="content-grid"><section className="info-block"><p className="eyebrow"><span/> Serve</p><h2>Best foods</h2><ul className="chip-list">{bird.foods.map(x=><li key={x}>{x}</li>)}</ul><p>Offer fresh food in small amounts and clean feeding surfaces regularly.</p></section><section className="info-block"><p className="eyebrow"><span/> Plant</p><h2>Useful plants</h2><ul className="chip-list">{bird.plants.map(x=><li key={x}>{x}</li>)}</ul><p>Confirm regional nativity and growing conditions before planting.</p></section><section className="info-block"><p className="eyebrow"><span/> Place</p><h2>Best feeders</h2><ul className="chip-list">{bird.feeders.map(x=><li key={x}>{x}</li>)}</ul><p>Provide visibility, nearby escape cover, and an easy cleaning routine.</p></section><section className="info-block"><p className="eyebrow"><span/> Identify</p><h2>Field marks</h2><p>{bird.identification??"Identification guidance is under editorial review."}</p></section><section className="info-block"><p className="eyebrow"><span/> Nest</p><h2>Nesting habits</h2><p>{bird.nestType?`A ${bird.nestType} nester, commonly using ${(bird.nestLocations??[]).join(", ")}. Typical clutch: ${bird.clutchSize??"varies"}.`:"Nesting information is under review."}</p></section><section className="info-block"><p className="eyebrow"><span/> Season</p><h2>Movement</h2><p>{bird.residentStatus}. Migration pattern: {bird.migrationPattern??"varies by population"}.</p></section><section className="info-block wide"><h2>Build a yard for {bird.commonName}s</h2><p>This profile passed the AttractBirds quality gate with a score of {bird.qualityScore}/100. Combine appropriate food, layered plants, clean water, and protective cover.</p><Link className="button button-primary" href="/#planner">Create my local plan <span>→</span></Link></section></div>
  </main><Footer/></div>
}
