import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Header } from "../../components/Header";
import { Footer } from "../../components/Footer";
import { featuredBirds, getBird } from "../../../lib/content";

export function generateStaticParams() { return featuredBirds.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug:string }> }): Promise<Metadata> { const bird=getBird((await params).slug); return bird ? { title:`${bird.commonName}: Diet & How to Attract`, description:`Learn where ${bird.commonName}s live, what they eat, and which plants and feeders can help attract them.` } : {}; }

export default async function BirdPage({ params }: { params: Promise<{ slug:string }> }) { const bird=getBird((await params).slug); if(!bird) notFound(); return <div><Header /><main className="content-main"><div className="breadcrumb"><Link href="/">Home</Link> / <Link href="/birds">Birds</Link> / {bird.commonName}</div><section className="content-hero"><div><p className="eyebrow"><span /> Bird profile</p><h1>{bird.commonName}</h1><p className="scientific">{bird.scientificName}</p><p className="lede">{bird.summary}</p></div><aside className="fact-panel"><div><small>Size</small><strong>{bird.size}</strong></div><div><small>Colors</small><strong>{bird.colors}</strong></div><div><small>Natural diet</small><strong>{bird.diet}</strong></div><div><small>Habitat</small><strong>{bird.habitat}</strong></div></aside></section><div className="content-grid"><section className="info-block"><p className="eyebrow"><span /> Serve</p><h2>Best foods</h2><ul className="chip-list">{bird.foods.map(x=><li key={x}>{x}</li>)}</ul><p>Offer fresh food in small amounts and clean feeding surfaces regularly.</p></section><section className="info-block"><p className="eyebrow"><span /> Plant</p><h2>Useful native plants</h2><ul className="chip-list">{bird.plants.map(x=><li key={x}>{x}</li>)}</ul><p>Check regional nativity and growing conditions before planting.</p></section><section className="info-block"><p className="eyebrow"><span /> Place</p><h2>Best feeders</h2><ul className="chip-list">{bird.feeders.map(x=><li key={x}>{x}</li>)}</ul><p>Place feeders where birds have a clear view and nearby escape cover, while following window-safety guidance.</p></section><section className="info-block"><p className="eyebrow"><span /> Protect</p><h2>Shelter and water</h2><p>Provide dense vegetation at several heights and a shallow, regularly cleaned water source. Reduce pesticide use so natural insect food remains available.</p></section><section className="info-block wide"><h2>Build a yard for {bird.commonName}s</h2><p>Combine suitable food, layered native vegetation, clean water, and low-disturbance shelter. Recommendations vary by location, yard size, and season.</p><Link className="button button-primary" href="/#planner">Create my local plan <span>→</span></Link></section></div></main><Footer /></div>; }
