import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Header } from "../../components/Header";
import { Footer } from "../../components/Footer";
import { getBirdBySlug, getBirdStaticParams, isBirdIndexEligible } from "../../../lib/bird-repository";

export function generateStaticParams(){return getBirdStaticParams()}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const bird=await getBirdBySlug((await params).slug);return bird?{title:`${bird.commonName}: Identification, Habitat & Diet`,description:`Learn the taxonomy, identification approach, habitat, diet, and regional status of ${bird.commonName} (${bird.scientificName}).`,alternates:{canonical:`/birds/${bird.slug}`},robots:isBirdIndexEligible(bird)?{index:true,follow:true}:{index:false,follow:true}}:{}}

export default async function BirdPage({params}:{params:Promise<{slug:string}>}){
  const bird=await getBirdBySlug((await params).slug);if(!bird)notFound();
  const isReviewed=isBirdIndexEligible(bird);
  return <div><Header/><main className="content-main"><div className="breadcrumb"><Link href="/">Home</Link> / <Link href="/birds">Birds</Link> / {bird.commonName}</div>
    <section className="content-hero"><div><p className="eyebrow"><span/> {isReviewed?"Reviewed bird profile":"Bird profile editorial queue"}</p><h1>{bird.commonName}</h1><p className="scientific">{bird.scientificName}</p><p className="lede">{bird.summary}</p></div>{bird.imageUrl?<figure className="bird-profile-image"><img src={bird.imageUrl} alt={bird.imageAlt??bird.commonName}/><figcaption>{bird.imageSourceUrl?<a href={bird.imageSourceUrl} target="_blank" rel="noreferrer">{bird.imageAttribution}</a>:bird.imageAttribution}{bird.imageLicenseUrl&&<> · <a href={bird.imageLicenseUrl} target="_blank" rel="noreferrer">License</a></>}</figcaption></figure>:<aside className="fact-panel"><div><small>Size</small><strong>{bird.size}</strong></div><div><small>Colors</small><strong>{bird.colors}</strong></div><div><small>Useful feeder foods</small><strong>{bird.diet}</strong></div><div><small>Habitat</small><strong>{bird.habitat}</strong></div></aside>}</section>
    {bird.imageUrl&&<aside className="fact-strip"><div><small>Size</small><strong>{bird.size}</strong></div><div><small>Colors</small><strong>{bird.colors}</strong></div><div><small>Useful feeder foods</small><strong>{bird.diet}</strong></div><div><small>Habitat</small><strong>{bird.habitat}</strong></div></aside>}
    {isReviewed?<div className="content-grid"><section className="info-block"><p className="eyebrow"><span/> Serve</p><h2>Best foods</h2><ul className="chip-list">{bird.foods.map(x=><li key={x}>{x}</li>)}</ul><p>Offer fresh food in small amounts and clean feeding surfaces regularly.</p></section><section className="info-block"><p className="eyebrow"><span/> Plant</p><h2>Useful plants</h2><ul className="chip-list">{bird.plants.map(x=><li key={x}>{x}</li>)}</ul><p>Confirm regional nativity and growing conditions before planting.</p></section><section className="info-block"><p className="eyebrow"><span/> Place</p><h2>Best feeders</h2><ul className="chip-list">{bird.feeders.map(x=><li key={x}>{x}</li>)}</ul><p>Provide visibility, nearby escape cover, and an easy cleaning routine.</p></section><section className="info-block"><p className="eyebrow"><span/> Identify</p><h2>Field marks</h2><p>{bird.identification??"Identification guidance is under editorial review."}</p></section><section className="info-block"><p className="eyebrow"><span/> Nest</p><h2>Nesting habits</h2><p>{bird.nestType?`${bird.nestType}; commonly using ${(bird.nestLocations??[]).join(", ")}. Typical clutch: ${bird.clutchSize??"varies"}.`:"Nesting information is under review."}</p></section><section className="info-block"><p className="eyebrow"><span/> Season</p><h2>Movement</h2><p>{bird.residentStatus}. Migration pattern: {bird.migrationPattern??"varies by population"}.</p></section><section className="info-block wide"><h2>Plan responsibly for {bird.commonName}</h2><p>Use this profile as a starting point, then confirm local range, seasonality, and species-specific feeding guidance before changing your yard.</p>{bird.sourceUrl&&<p><a href={bird.sourceUrl} target="_blank" rel="noreferrer">View the AOS taxonomy record ↗</a></p>}<Link className="button button-primary" href="/#planner">Create my local plan <span>→</span></Link></section></div>:null}
  </main><Footer/></div>
}
