export const featuredBirds = [
  { slug: "northern-cardinal", commonName: "Northern Cardinal", scientificName: "Cardinalis cardinalis", initials: "NC", family: "Cardinalidae", hook: "A year-round flash of red", colors: "Crimson red, warm brown, black mask", size: "21–23.5 cm", diet: "Seeds, fruit, and insects", habitat: "Shrubby woodland edges, gardens, and thickets", foods: ["Black-oil sunflower seeds", "Safflower", "Cracked corn", "Berries"], plants: ["American dogwood", "American elderberry", "Serviceberry"], feeders: ["Platform feeder", "Large hopper feeder"], summary: "Northern Cardinals are non-migratory songbirds known for their clear whistles and preference for dense, low cover. A combination of sturdy feeders, sunflower seed, berry-producing shrubs, and fresh water can make a yard more inviting." },
  { slug: "american-robin", commonName: "American Robin", scientificName: "Turdus migratorius", initials: "AR", family: "Turdidae", hook: "The familiar lawn forager", colors: "Gray-brown, orange breast, white eye ring", size: "23–28 cm", diet: "Earthworms, insects, and fruit", habitat: "Lawns, parks, gardens, and open woodland", foods: ["Mealworms", "Fruit", "Raisins softened in water"], plants: ["Serviceberry", "Crabapple", "Winterberry"], feeders: ["Ground tray", "Platform feeder"], summary: "American Robins often forage on open ground and rely heavily on fruit outside the breeding season. Avoiding lawn chemicals and planting fruiting native trees supports them better than seed alone." },
  { slug: "blue-jay", commonName: "Blue Jay", scientificName: "Cyanocitta cristata", initials: "BJ", family: "Corvidae", hook: "Bold, clever, and unmistakable", colors: "Blue, white, and black", size: "25–30 cm", diet: "Nuts, seeds, insects, and fruit", habitat: "Oak woodland, suburbs, and forest edges", foods: ["Peanuts", "Sunflower seeds", "Suet"], plants: ["Native oak", "American beech", "Serviceberry"], feeders: ["Platform feeder", "Peanut feeder"], summary: "Blue Jays are intelligent, social birds with a strong preference for nuts. Mature native oaks, a stable platform feeder, and whole or shelled peanuts are powerful attractants." },
  { slug: "american-goldfinch", commonName: "American Goldfinch", scientificName: "Spinus tristis", initials: "AG", family: "Fringillidae", hook: "A bright visitor to seed heads", colors: "Yellow, black, and olive-brown", size: "11–13 cm", diet: "Primarily seeds", habitat: "Weedy fields, gardens, and open woodland", foods: ["Nyjer", "Sunflower chips"], plants: ["Purple coneflower", "Sunflower", "Native thistle"], feeders: ["Finch tube feeder", "Mesh feeder"], summary: "American Goldfinches specialize in seeds and readily visit gardens where spent flower heads remain standing. Nyjer feeders and pesticide-free native flowers offer reliable food." },
];

export const plantPicks = [{ title: "12 native flowers hummingbirds return to", summary: "Build a long-blooming nectar corridor with flowers suited to your region, light, and available space." }];
export const problemGuides = [
  { title: "Why did birds stop coming to my feeder?", summary: "Seven common causes—from spoiled seed to seasonal food—and the quickest checks to make.", href: "/bird-problems/no-birds-at-feeder" },
  { title: "Where should a platform feeder go?", summary: "Balance visibility, escape cover, window safety, and easy cleaning with a practical placement checklist.", href: "/feeders/platform-feeder" },
];

export function getBird(slug: string) { return featuredBirds.find((bird) => bird.slug === slug); }
